### ISSUE TITLE
Fix faces/apps menu display

### ISSUE THREAD

**Issue by strdr4605** [pebble-dev/rebble-store#133]
It would be better if faces/apps menu will not overlay search and other elements.
<img width="844" alt="screen shot 2018-07-01 at 16 06 43" src="https://user-images.githubusercontent.com/16056918/42135717-511be1a0-7d4f-11e8-83f0-e18b72e10504.png">
At least hide the menu on page change or move elements lower.

**Comment by strdr4605** [comment]
@sGerli, what do you suggest? hide the menu on page change, move elements lower or something else?

**Comment by sGerli** [comment]
I've been thinking about this and I'm actually not sure what to do
