### ISSUE TITLE
Algolia search query-parameters not updating results

### ISSUE THREAD

**Issue by sGerli** [pebble-dev/rebble-store#138]
- Pages don't change according to route
- Search filters require a reload

**Comment by phosphotungstic** [comment]
Hi! Has this been fixed? It seems to be working fine though I found something else where if you completely clear the search bar, it 404s on you.

**Comment by sGerli** [comment]
Last time I checked that wasn’t the behavior, but who knows, right now I’m on vacation but I’ll try to confirm that

**Comment by phosphotungstic** [comment]
Any word on if you've tried it out?

**Comment by sGerli** [comment]
You're right clearing the search bar 404s  because the address gets changed to `:type/search/:page`, it's missing the query, it should reset to `:type/search/`. But the search filters still don't update results until reload. Also, last time I dived into the code I was unable to bind back the search page to Algolia.
