### ISSUE TITLE
Get button to download the app is not working

### ISSUE THREAD

**Issue by shubhang93** [pebble-dev/rebble-store#161]
I am using the app on iOS and the get button to download the app on the rebble store is not downloading the app.

**Comment by pelletencate** [comment]
I got the same issue. I have to surf now to apps.rebble.io using Safari on my phone, download the PBW file and send it to the Pebble app. It seems that the `pebble://` links won't work. 

Clicking 'Get' in the store doesn't do anything, and manually opening a `pebble://` link from the website opens the Pebble app, which subsequently pops up an all white screen.

**Comment by sGerli** [comment]
I've confirmed there's a problem that wasn't there before. I'll be taking a more in-depth look at it soon in order to fix it.

**Comment by sGerli** [comment]
Fixed by #171 
What @pelletencate reported is in #172
