### ISSUE TITLE
The button to "view all" is missing from the watchfaces store

### ISSUE THREAD

**Issue by ruralTom** [pebble-dev/rebble-store#164]
When I go to browse the watch faces in the rebblestore the. "see all" option is missing from all but the generated watch faces.

[Link to photo showing what the heck I am speaking of](https://i.imgur.com/hVo1vQ7.png)

**Comment by sGerli** [comment]
This issue is not related to this repo (fontend), this is a known backend issue related to https://github.com/pebble-dev/rebble-appstore-api/issues/2

I'm going to close this issue because there's already a related issue in there.
