### ISSUE TITLE
"Website Link" shows up for apps that don't have a website

### ISSUE THREAD

**Issue by halkeye** [pebble-dev/rebble-store#165]
CSS is broken because a tags without href are not considered links by browser, and thus wrong cursor

Clicking on it gives you a new link to "null"

Example: /#/app/5b02f29f461a8dd931000e5a

**Comment by mhelmetag** [comment]
Would anyone be able to run a query on the DB to see if some website URLs are an empty string? It seems like they're usually `null` (so PG `nil`).

I think if [this line](https://github.com/pebble-dev/rebble-store/blob/master/src/components/pages/AppDetails.vue#L34) is changed to either be just a null check or a blank and null check, that'll work. Whichever works better depending on the data (not sure if it's a field that has a validation against empty strings or just a free for all).

**Comment by mhelmetag** [comment]
I think also any time it's an external link the cursor is technically wrong. Or at least that's what I'm seeing in a few places across the app. So I think those are two separate issues.
