### ISSUE TITLE
Add Screenshots

### ISSUE THREAD

**Issue by sGerli** [pebble-dev/rebble-store#18]
Add screenshots to the App Detail Page.
Must be like the screenshot slider from the Pebble App Store.
Must have no background color and must be mobile friendly.

**Comment by aveao** [comment]
You know, I never liked the slider in pebble store. It was... too bulky, too big. It covered half my screen for no good reason. 

I propose doing something smaller.

---

![screenshot from 2016-12-12 01-42-09](https://cloud.githubusercontent.com/assets/6755762/21083979/4b190c24-c004-11e6-9dd9-3b5f5497c5d0.png)

As you can see, actual screenshot is only slightly bigger than 1/3 of the reserved area.

**Comment by sGerli** [comment]
Ok, @JohannesNeubrand proposed to do something smaller, without the frame, but still with sidescrolling.
