### ISSUE TITLE
Add Icons to UI

### ISSUE THREAD

**Issue by PotatoFi** [pebble-dev/rebble-store#26]
These icons aren't specific designed for the higher resolutions, but I wanted to provide them anyway, just in case.

[SVG's.zip](https://github.com/pebble-dev/The-Panic-Store/files/647956/SVG.s.zip)

25px:
![calendar 25px](https://cloud.githubusercontent.com/assets/19558338/21126701/1858b2a6-c0ab-11e6-896c-0cf3f817b3df.png)
64px:
![calendar 64px](https://cloud.githubusercontent.com/assets/19558338/21126703/1ba62fc4-c0ab-11e6-8276-2c549b260cb1.png)
128px:
![calendar 128px](https://cloud.githubusercontent.com/assets/19558338/21126706/1d92bd3e-c0ab-11e6-8c7e-a27d28d34fce.png)
256px:
![calendar 256px](https://cloud.githubusercontent.com/assets/19558338/21126708/1f81e020-c0ab-11e6-8cd1-560669f76ede.png)
![heart25px](https://cloud.githubusercontent.com/assets/19558338/21126710/24197698-c0ab-11e6-9fa0-8821fea417ac.png)
![heart64px](https://cloud.githubusercontent.com/assets/19558338/21126713/270b92dc-c0ab-11e6-80a0-1c5497e261ab.png)
![heart128px](https://cloud.githubusercontent.com/assets/19558338/21126714/29f26124-c0ab-11e6-91ca-2c47ae61dbcf.png)
![heart256px](https://cloud.githubusercontent.com/assets/19558338/21126715/2bb841ea-c0ab-11e6-9e60-6aef26c6813c.png)
![heartred 25px](https://cloud.githubusercontent.com/assets/19558338/21126743/57dd5684-c0ab-11e6-84b7-5c4f715b7be1.png)
![heartred 64px](https://cloud.githubusercontent.com/assets/19558338/21126745/5a2ff1da-c0ab-11e6-80be-5a1bb488a142.png)
![heartred 128px](https://cloud.githubusercontent.com/assets/19558338/21126746/5c148614-c0ab-11e6-8a40-729ecce2f42c.png)
![heartred 256px](https://cloud.githubusercontent.com/assets/19558338/21126748/5e13e7b6-c0ab-11e6-9120-6372ae1a61b5.png)
![download25px](https://cloud.githubusercontent.com/assets/19558338/21126795/bb3c5c84-c0ab-11e6-83a8-4f5090f79c11.png)
![download64px](https://cloud.githubusercontent.com/assets/19558338/21126796/bda08fcc-c0ab-11e6-9ab8-1262025e52d0.png)
![download128px](https://cloud.githubusercontent.com/assets/19558338/21126797/c0acb4a2-c0ab-11e6-9aae-961f67f6fee2.png)
![download256px](https://cloud.githubusercontent.com/assets/19558338/21126798/c284df34-c0ab-11e6-8333-ff86ba995286.png)
![search](https://cloud.githubusercontent.com/assets/19558338/21126828/f38fc85a-c0ab-11e6-9a0b-cf41603143b4.png)
![search64px](https://cloud.githubusercontent.com/assets/19558338/21126829/f4690390-c0ab-11e6-8a20-48fdacf7a434.png)
![search128px](https://cloud.githubusercontent.com/assets/19558338/21126830/f57475ee-c0ab-11e6-9ed9-12a647867f12.png)
![search256px](https://cloud.githubusercontent.com/assets/19558338/21126832/f6c3c38c-c0ab-11e6-96d5-76bec8fa16b6.png)
![thumbs up](https://cloud.githubusercontent.com/assets/19558338/21126883/48ddc3d4-c0ac-11e6-9b79-301e252f53aa.png)
![thumbs up64px](https://cloud.githubusercontent.com/assets/19558338/21126886/49f98348-c0ac-11e6-9570-617e7061f07a.png)
![thumbs up128px](https://cloud.githubusercontent.com/assets/19558338/21126887/4b357a6e-c0ac-11e6-8857-55016f5a37f5.png)
![thumbs up256px](https://cloud.githubusercontent.com/assets/19558338/21126888/4d5a0b2a-c0ac-11e6-8cfa-2bfb659ea72e.png)

**Comment by sGerli** [comment]
@PotatoFi Can you also put here the App and Watchface icons?

**Comment by PotatoFi** [comment]
@sGerli Here are the App and Watchface icons in SVG. Forgot about these the first time around. :)

[App and Watchface SVGs.zip](https://github.com/pebble-dev/The-Panic-Store/files/649601/App.and.Watchface.SVGs.zip)

![watchface25px](https://cloud.githubusercontent.com/assets/19558338/21151211/e359e1e6-c11e-11e6-84ec-36534185b628.png)
![watchface64px](https://cloud.githubusercontent.com/assets/19558338/21151214/e4862048-c11e-11e6-96ef-ba0d602a7e89.png)
![watchface128px](https://cloud.githubusercontent.com/assets/19558338/21151217/e5cdac14-c11e-11e6-84a7-90ee3ab6c3d7.png)
![watchface256px](https://cloud.githubusercontent.com/assets/19558338/21151220/e725c54c-c11e-11e6-884b-8526a7b52838.png)
![app25px](https://cloud.githubusercontent.com/assets/19558338/21151259/127a35ca-c11f-11e6-8e1d-7f32bdbf1c71.png)
![app64px](https://cloud.githubusercontent.com/assets/19558338/21151261/13723400-c11f-11e6-8661-0538965f5512.png)
![app128px](https://cloud.githubusercontent.com/assets/19558338/21151264/147ce386-c11f-11e6-9cc4-f240021194eb.png)
![app256px](https://cloud.githubusercontent.com/assets/19558338/21151267/159b405a-c11f-11e6-941e-719ae22a698e.png)

**Comment by PotatoFi** [comment]
[App and Watchface SVGs.zip](https://github.com/pebble-dev/The-Panic-Store/files/649619/App.and.Watchface.SVGs.zip)
![app25px](https://cloud.githubusercontent.com/assets/19558338/21151368/7cf5fa1a-c11f-11e6-9d2a-62cfb1366b88.png)
![app64px](https://cloud.githubusercontent.com/assets/19558338/21151369/7ddeade6-c11f-11e6-8388-260c3ae8eb92.png)
![app128px](https://cloud.githubusercontent.com/assets/19558338/21151372/7ea765d8-c11f-11e6-86f8-a6b3a0ed4645.png)
![app256px](https://cloud.githubusercontent.com/assets/19558338/21151373/7fcfba78-c11f-11e6-8b8b-22d2c5e0d0f0.png)
![watchface25px](https://cloud.githubusercontent.com/assets/19558338/21151387/8ff5375c-c11f-11e6-95c4-fe000296880d.png)
![watchface64px](https://cloud.githubusercontent.com/assets/19558338/21151389/90e03400-c11f-11e6-9c6e-9558b2c78e22.png)

Watchface icon needs additional work to look good at higher resolutions. Let me know if this is needed.

**Comment by sGerli** [comment]
I think that works, thanks

**Comment by sGerli** [comment]
Done in #30
