### ISSUE TITLE
app-details/app-version needs title centered, DL SVG fix

### ISSUE THREAD

**Issue by KonradIT** [pebble-dev/rebble-store#37]
### Main page, centered:
![imagen](https://cloud.githubusercontent.com/assets/5891284/21356177/efcd5f4a-c6d0-11e6-9000-140b61de57f1.png)

### App-details, not centered

![imagen](https://cloud.githubusercontent.com/assets/5891284/21356200/089939ea-c6d1-11e6-8543-ac48106d718d.png)

### Download button gfx is broken (Firefox 50 on Windows 10)

![sin titulo](https://cloud.githubusercontent.com/assets/5891284/21356235/26e07c92-c6d1-11e6-89a5-597271f550f7.png)

**Comment by sGerli** [comment]
Download button is broken in all browsers and I can confirm it's not a CSS issue, I disabled CSS and the issue was still there.

**Comment by sGerli** [comment]
SVG are in #26 I changed the colors in the icon and changed the fill to none

**Comment by Zetaphor** [comment]
Looks even worse for me in Chrome 55 on Linux :cry:

![image](https://cloud.githubusercontent.com/assets/3112763/21357132/1c0b4678-c6a2-11e6-89e4-0649f01c3630.png)

**Comment by aveao** [comment]
the reason download button looks like that seems like someone tried to hack together a get icon by joining 2 rectangles with the down emoji.

See Rectangle-10 and Rectangle-11 on https://github.com/pebble-dev/The-Panic-Store/blob/master/src/app-details.html#L124

Also, can repro all on Firefox 50.1.0 on Ubuntu 16.10

**Comment by sGerli** [comment]
And the centering issues are probably due to the back button.

**Comment by sGerli** [comment]
Fixed Centering issue in #38

**Comment by KonradIT** [comment]
Fixed download icon in 740525e9

**Comment by sGerli** [comment]
@KonradIT Can you use a better implementation of the SVG like in the Thumbs Up button in which we can change the colors depending on the hover state?

**Comment by KonradIT** [comment]
@sGerli the colors already change on hover:

![pebble](https://cloud.githubusercontent.com/assets/5891284/21438510/b6e1dbe2-c889-11e6-8ae4-3056fbfa5ad3.gif)

**Comment by sGerli** [comment]
Yes I know they change but that's not how they're supposed to, they are supposed to invert bg and fill colors link in this screenshot:
![img_4249](https://cloud.githubusercontent.com/assets/3890044/21440522/fec002da-c858-11e6-914b-014e2f0277d9.PNG)

But don't worry about doing any change in master until vue is merged into master. (Zetaphor was trying to fix that on the vue branch)

**Comment by Zetaphor** [comment]
@sGerli This has been fixed in the vue branch.
