### ISSUE TITLE
App card layout broken on Android

### ISSUE THREAD

**Issue by KonradIT** [pebble-dev/rebble-store#39]
The app list on index.html, apps.html, featured.html are broken on Android, tested with Firefox 50.1.0 

Screenshots:

![Screenshot_20161220-213906.png](http://i.imgur.com/DPxLXQ9.png)

![Screenshot_20161220-213956.png](http://i.imgur.com/HZIkzoj.png)

**Comment by mvaneijgen** [comment]
Prefixes are missing on `column-count: 3;`. I think it's a good idea to implement a autoprefixer within `grunt` or `webpack` to prevent these kind of issues. 

Agian

**Comment by Zetaphor** [comment]
@mvaneijgen Autoprefixer is included in the webpack build on the vue branch.

**Comment by mvaneijgen** [comment]
@Zetaphor cool. So this issue can be closed of than?
