### ISSUE TITLE
Move all SVG references to external files

### ISSUE THREAD

**Issue by Zetaphor** [pebble-dev/rebble-store#47]
There's a number of repeated inline SVG's on the current vue branch.

These can all be moved to external files to reduce duplication and allow browser caching.

**Comment by sGerli** [comment]
Yes, that's right but there's no way of changing styles on external SVG that I'm aware of.

**Comment by Zetaphor** [comment]
Fixed in #50 

@sGerli Not sure what you are referring to. I just pushed the change and all CSS styles are still applied to the SVG's correctly. Additionally this has resolved the issue with Chrome gnashing up the download icon:

![image](https://cloud.githubusercontent.com/assets/3112763/21432977/058b3782-c83c-11e6-8646-f860ad67304e.png)
