### ISSUE TITLE
api.rebble.io and docs.rebble.io

### ISSUE THREAD

**Issue by TheTechmage** [pebble-dev/rebble-store#51]
It would be nice (at least during the development stages) if we code have the API documentation and the APIs both online and easily accessible. I propose that the domain names both being api.rebble.io and docs.rebble.io.

I have a server that can serve the content of both of those at 23.94.164.141 and can host the services (at the least, during development).

Thought? @afourney, @sGerli, @ishotjr?

**Comment by sGerli** [comment]
I Think it's a good idea

**Comment by TheTechmage** [comment]
I switched the issue description from `doc` to `docs` because I realized how much more common the plural version was over the singular version.

**Comment by ishotjr** [comment]
@frostyfrog so just to confirm, all you need is a `CNAME` for each, pointing at that IP?  Are the corresponding services up now?  Thanks!! :bowtie:

**Comment by TheTechmage** [comment]
Not sure if a CNAME will work against an IP (I could provide a DNS entry if needed), but yeah. Basically. I've made sure that the services are online and available via the aforementioned IP.

**Comment by ishotjr** [comment]
@frostyfrog sorry, must have been having some kind of brain error - *`A`* records added and are already resolving! 😅 

http://api.rebble.io/
http://docs.rebble.io/
