### ISSUE TITLE
Transition to new backend repo

### ISSUE THREAD

**Issue by Zetaphor** [pebble-dev/rebble-store#53]
sGerli has setup a [new backend repo exclusively for API work](https://github.com/pebble-dev/rebblestore-backend).

This will serve to clean up the commit tree and make it simpler for new developers to jump into the area of development relevant to their domain.

**Comment by Zetaphor** [comment]
Thanks @frostyfrog!

Do we want to delete the dev/backend branch, or just note in the readme that it's moved?

**Comment by TheTechmage** [comment]
I didn't even notice that this ticket existed. I don't think that I have the ability to remove a branch, but I think that it's the approach that should be taken.

**Comment by sGerli** [comment]
Done, the `dev/backend` branch is gone.
