### ISSUE TITLE
Rebuild SVGs used on the site with SVGO compressor (for Sketch OSX)

### ISSUE THREAD

**Issue by mvaneijgen** [pebble-dev/rebble-store#57]
The current SVG files look nice, but have a lot of unnecessary code within them. Saving SVGs from Sketch (OSX only) with the [SVGO compressor](https://github.com/BohemianCoding/svgo-compressor) plugin will strip all the unnecessary code automatically.

Next we need to name the files (with a unique name) which is going to be used to call the SVG files within the site. 

PS: I am really picky with SVG code, I don't like unnecessary `<g>` tags so I am going to remove them.

**Comment by Zetaphor** [comment]
A huge :+1: to this. Today was my first time looking through SVG markup, and all the extraneous tags weren't helping my comprehension :-D
