### ISSUE TITLE
Order of SVG's in DOM affects rendering

### ISSUE THREAD

**Issue by Zetaphor** [pebble-dev/rebble-store#61]
I'm not sure what to make of this. If the iconApp SVG is below any other SVG, it looks broken to varying degrees.

Here's an example with it below iconSearch in the SvgContainer component:
![image](https://cloud.githubusercontent.com/assets/3112763/21445993/db222264-c88e-11e6-9146-326fd0b26475.png)

And here it is moved to the top of the SvgContainer component:
![image](https://cloud.githubusercontent.com/assets/3112763/21446009/059487bc-c88f-11e6-8f16-2262db65946a.png)

Similarly, if the pet rock SVG is included, it looks even more broken :cry: 

@mvaneijgen Could this possibly be related to #57? Going to assign you on this as well, since you have more domain knowledge.

**Comment by Zetaphor** [comment]
It just dawned on me, that first screenshot kind of looks like it has the arrow from the download icon inside of it. When the SVG was below iconSearch, it was *also* beneath iconDownload. Could that be the culprit?

**Comment by mvaneijgen** [comment]
PR https://github.com/pebble-dev/rebble-store/pull/63  should fix this. Included to screenshots below what it looks like on my local machine 
![rebble_app_store](https://cloud.githubusercontent.com/assets/3217544/21449721/7d371c88-c8f0-11e6-973b-fc7f14bfacfd.jpg)
![rebble_app_store](https://cloud.githubusercontent.com/assets/3217544/21449724/84c42676-c8f0-11e6-804b-be80a80591a1.jpg)

**Comment by sGerli** [comment]
Going to test and then close

**Comment by Zetaphor** [comment]
@mvaneijgen Fixed all the things! :heart: 
Though I'd really like to know *why* they were broken. What was wrong with the SVG syntax before this PR?
