### ISSUE TITLE
Add documentation and dependency for Windows (WSL) users

### ISSUE THREAD

**Issue by Zetaphor** [pebble-dev/rebble-store#65]
@sGerli has succesfully setup a dev environment in Windows 10 using the [Windows Subsystem for Linux](https://msdn.microsoft.com/commandline/wsl/about) (WSL). This required the addition of a patched version of the node-macaddress package.

This package needs to be added to the dev section of package.json, and the README updated to reflect the process for Windows users.

**Comment by sGerli** [comment]
It's not that macadress package, I'll do this later.

**Comment by Zetaphor** [comment]
[Here is the post](https://github.com/AngularClass/angular2-webpack-starter/issues/1273) @sGerli referred to when discussing the fix in Discord.

Removed the package link from my original post since this requires a specific patch.

And here's the comment where he explained the fix:
```
1.  Install node-macadress (this version only): npm install github:TheBeastOfCaerbannog/node-macaddress.git#43238cd0569573837d4b48a27b3063d287d2968b
2. If you get an error saying that  node-sass/vendor  was not found run npm rebuild node-sass
And that should work if you installed correctly vue cli
```

**Comment by sGerli** [comment]
Added in #70 , so now this is done
