### ISSUE TITLE
Better way of including SASS variables. Now they need to be included in all components using @import './static/css/_variables.scss'; 

### ISSUE THREAD

**Issue by mvaneijgen** [pebble-dev/rebble-store#67]
I had a lot of trouble getting the SASS variables in the site. The only way I found is adding `@import './static/css/_variables.scss';` at the top of the `<style>` tag in each compontent. There must be a better way, but may Google-fu wasn't their today.

**Comment by Zetaphor** [comment]
I too was looking for something like this recently, and was basically told that I'm screwed :-(

I'll do some more googling and see if I can either find that post, or something useful

**Comment by Zetaphor** [comment]
[Found it!](https://github.com/vuejs/vue-loader/issues/328) Lots of good discussion there.
