### ISSUE TITLE
Backend development work

### ISSUE THREAD

**Issue by bbenne10** [pebble-dev/rebble-store#69]
Before realizing that this work was ongoing here, I started my own project to expose the archive of the pebble store to the internet. I'm not overly fond of Vue.js and the like (and I do enough JS development at work...), but I do have some basic work completed which might interest you all. 

So far I have a basic Flask application that allows for full text searches over the current store, and I have begun work on the single-application view page. I've picked PostgreSQL for the ease with which one can implement full-text searches (ala ElasticSearch) using TSVector and TSQuery. Admittedly, I did a straight port of the schema that is present in the ripped JSON files (so categories are singular), but I did drop the "type" field (as it was covered by a category). If there's interest, we should start discussing the level of coupling between the front and back ends and the like.

**Comment by sGerli** [comment]
Hi @bbenne10 we are also working on the backend but on Go lang on the rebblestore-api repo, you can also find us on our Discord server to have a talk with all of us. http://rebble.io

**Comment by Zetaphor** [comment]
@bbenne10 I'm definitely interested in checking out what you have so far. Is there a repo you can point me to?

**Comment by bbenne10** [comment]
@Zetaphor: Find the work I have completed thus far [here](https://github.com/bbenne10/pebble_store). It's not much, but it gets the ball rolling on my end. I'm home from work all of this week and will likely hop into the discord channel for a bit to discuss. Thanks for showing some interest.

**Comment by TheTechmage** [comment]
Sorry for not responding to this sooner @bbenne10. @Zetaphor just barely pointed this ticket out to me via discord. I've been working on the API within [rebblestore-api](https://github.com/pebble-dev/rebblestore-api) and haven't quite been paying attention to the issues that have been popping up in here. I'd be more than happy to discuss more with you if you have the time! (I'm currently the sole person actively working on the backend. It'd be nice to have some help!) :smile:
