### ISSUE TITLE
Add Back Button To Vue

### ISSUE THREAD

**Issue by sGerli** [pebble-dev/rebble-store#72]
1. Add back button on all pages except App's home and Watchface's home.

![back](https://cloud.githubusercontent.com/assets/3890044/21486653/dbfede56-cb7d-11e6-9cd7-19883e7f19e7.PNG)

The back button code is: (Goes inside navbar like in [here](https://github.com/pebble-dev/rebble-store/blob/master/src/featured.html#L33))
```html
<div class="navbar__items left">
   <a class="float-xs-left back" href="app-details.html"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
</div>
```

**Comment by Zetaphor** [comment]
Fixed in #77
