### ISSUE TITLE
Make UI Work With The Backend

### ISSUE THREAD

**Issue by sGerli** [pebble-dev/rebble-store#97]
- [ ]  Fetch watchfaces page

- [ ] Fetch watchfaces slider images/categories

- [ ] Make watchfaces categories view all button work

- [ ] Fetch apps page

- [ ] Fetch apps slider images/categories

- [x] Fetch app tags

- [ ] Make app categories view all button work

- [ ] Make author pages work

- [x] Make search work

- [ ] Implement pagination or infinite scroll

- [x] Fetch app/watchface details

- [x] Fetch app versions

All of this has to be done with the [rebblestore-api](https://github.com/pebble-dev/rebblestore-api).

**Comment by sGerli** [comment]
Most of the backend endpoints have already been implemented by the awesome @pebble-dev/go-lang-backend team, so it's time to continue development

**Comment by tomholford** [comment]
Would like to contribute if possible. Lots of experience with Angular, but also interested in learning Vue. Are there any small / self-contained tasks I could take a crack at?

**Comment by sGerli** [comment]
@tomholford if you want to contribute just make a PR and it would be great if you joined our Discord server

**Comment by sGerli** [comment]
We decided not to use our API, instead replicate the Pebble app store API
